'use strict'

/**
 * DHS API Usage — Host half
 *
 * Two jobs:
 *  1. Listen to the `llm/stream` waterfall and fold every real model call's
 *     provider-reported token usage into in-memory hourly/daily buckets.
 *  2. Resolve the deployment's DeepSeek credential (`DEEPSEEK_API_KEY`) and
 *     query the official `/user/balance` endpoint for the account balance.
 *
 * The Client half (`client/bundle.js`) fetches the JSON snapshot from the
 * HTTP route registered below (`/ds-api-usage/snapshot`) and renders the
 * settings page.
 *
 * Communication is deliberately NOT the dynamic-package `harness.handle` /
 * `host.call` pair: that channel exists only inside the dynamic Cordis
 * sandbox. As a static bundle installed via `dsh plugin add`, the host half
 * exposes an HTTP endpoint through the `webServer` service instead, and the
 * browser half calls it with plain `fetch` (the bundle runs in the real
 * page, not a sandbox).
 *
 * Note: token counts come straight from the provider-reported `usage` chunk
 * (cache hit / miss are already disjoint, matching DeepSeek's own billing
 * vocabulary). The cost figure is an ESTIMATE in CNY computed from
 * DeepSeek's public list prices; see the generated PRICING block below
 * (auto-updated by .github/scripts/update-pricing.mjs; peak/off-peak rates
 * are selected by each request's UTC hour).
 */

// ── pricing table ────────────────────────────────────────────────────────────
// Generated by .github/scripts/update-pricing.mjs from the official DeepSeek
// pricing page — do not edit by hand (run `npm run update:pricing`).
// Cache write is not billed separately by DeepSeek, so it is excluded.
// __PRICING_BEGIN__
const PRICING = {
  "source": "https://api-docs.deepseek.com/zh-cn/quick_start/pricing/",
  "currency": "CNY",
  "peakHoursUtc": [
    [
      1,
      4
    ],
    [
      6,
      10
    ]
  ],
  "rates": {
    "deepseek-v4-flash": {
      "flat": {
        "hit": 0.02,
        "miss": 1,
        "output": 2
      },
      "offPeak": {
        "hit": 0.05,
        "miss": 1.5,
        "output": 4.5
      },
      "peak": {
        "hit": 0.1,
        "miss": 3,
        "output": 9
      }
    },
    "deepseek-v4-pro": {
      "flat": {
        "hit": 0.025,
        "miss": 3,
        "output": 6
      },
      "offPeak": {
        "hit": 0.15,
        "miss": 4.5,
        "output": 13.5
      },
      "peak": {
        "hit": 0.3,
        "miss": 9,
        "output": 27
      }
    },
    "deepseek-chat": {
      "flat": {
        "hit": 0.5,
        "miss": 2,
        "output": 8
      },
      "carriedOver": true
    },
    "deepseek-reasoner": {
      "flat": {
        "hit": 1,
        "miss": 4,
        "output": 16
      },
      "carriedOver": true
    }
  }
}
// __PRICING_END__

const DEFAULT_RATE = (PRICING.rates['deepseek-v4-flash'] && (PRICING.rates['deepseek-v4-flash'].flat || PRICING.rates['deepseek-v4-flash'].offPeak))
  || { hit: 0.02, miss: 1, output: 2 }

// Pick the rate for a model at a given timestamp: models with peak/off-peak
// data are priced by the request's UTC hour (windows from the generated
// table); everything else falls back to its flat rate.
function rateFor(model, ts) {
  const entry = PRICING.rates[model]
  if (!entry) return DEFAULT_RATE
  if (entry.peak && entry.offPeak) {
    const h = new Date(ts).getUTCHours()
    const windows = Array.isArray(PRICING.peakHoursUtc) && PRICING.peakHoursUtc.length === 2
      ? PRICING.peakHoursUtc
      : [[1, 4], [6, 10]]
    const peak = windows.some((w) => h >= w[0] && h < w[1])
    return peak ? entry.peak : entry.offPeak
  }
  return entry.flat || DEFAULT_RATE
}
const HOURLY_KEEP_MS = 48 * 3600 * 1000
const DAILY_KEEP_MS = 14 * 86400 * 1000

// ── persistence ───────────────────────────────────────────────────────────────
// Hourly/daily buckets are persisted to `$DSH_HOME/storages/ds-api-usage.json`
// so the 14-day view survives web-app restarts. Writes are debounced (max one
// per 60 s) and flushed synchronously on plugin dispose; any read/write error
// is swallowed so persistence never breaks accounting. The dynamic sandbox
// form has no node:fs — there persistence is skipped silently.
let fsMod = null
let osMod = null
let pathMod = null
try {
  fsMod = require('node:fs')
  osMod = require('node:os')
  pathMod = require('node:path')
} catch (e) { /* sandboxed dynamic form: no fs */ }

function bucketsFilePath() {
  if (!fsMod || !pathMod) return null
  const home = process.env.DSH_HOME || (osMod.homedir() + '/.dsh')
  return home ? pathMod.join(home, 'storages', 'ds-api-usage.json') : null
}

function serializeBuckets(hourly, daily) {
  return { v: 1, hourly: [...hourly.values()], daily: [...daily.values()] }
}

function parseBuckets(json) {
  if (!json || json.v !== 1) return null
  const valid = (b) => b && typeof b === 'object'
    && Number.isFinite(b.ts) && Number.isFinite(b.requests)
    && Number.isFinite(b.inputTokens) && Number.isFinite(b.outputTokens)
    && Number.isFinite(b.cacheReadTokens) && Number.isFinite(b.cacheWriteTokens)
    && Number.isFinite(b.reasoningTokens) && Number.isFinite(b.costCny)
  const hourly = new Map()
  const daily = new Map()
  for (const b of Array.isArray(json.hourly) ? json.hourly : []) if (valid(b)) hourly.set(b.ts, b)
  for (const b of Array.isArray(json.daily) ? json.daily : []) if (valid(b)) daily.set(b.ts, b)
  return { hourly, daily }
}

// Seed missing keys only: in-memory data (current session) always wins.
function mergeMaps(target, source) {
  for (const [ts, bucket] of source) if (!target.has(ts)) target.set(ts, bucket)
}

function pruneMaps(hourly, daily, now) {
  for (const k of hourly.keys()) if (k < now - HOURLY_KEEP_MS) hourly.delete(k)
  for (const k of daily.keys()) if (k < now - DAILY_KEEP_MS) daily.delete(k)
}

module.exports = {
  name: 'ds-api-usage',
  inject: ['timer', 'webServer'],
  // Exposed for the offline test suite only (test/pricing.test.mjs); Cordis
  // ignores unknown export properties.
  __test: { PRICING, DEFAULT_RATE, rateFor, serializeBuckets, parseBuckets, mergeMaps, pruneMaps, bucketsFilePath },

  apply(ctx) {
    const hourly = new Map()
    const daily = new Map()
    const startedAt = Date.now()

    // ── load persisted buckets (if any), then prune stale windows ─────────────
    const bucketsFile = bucketsFilePath()
    if (bucketsFile && fsMod.existsSync(bucketsFile)) {
      try {
        const loaded = parseBuckets(JSON.parse(fsMod.readFileSync(bucketsFile, 'utf8')))
        if (loaded) {
          mergeMaps(hourly, loaded.hourly)
          mergeMaps(daily, loaded.daily)
        }
      } catch (e) { /* corrupted file: start fresh */ }
    }
    pruneMaps(hourly, daily, Date.now())

    let dirty = false
    const persist = () => {
      if (!dirty || !bucketsFile || !fsMod) return
      try {
        const tmp = bucketsFile + '.tmp'
        fsMod.writeFileSync(tmp, JSON.stringify(serializeBuckets(hourly, daily)))
        fsMod.renameSync(tmp, bucketsFile)
        dirty = false
      } catch (e) { /* persistence must never break accounting */ }
    }
    ctx.interval(() => { if (dirty) persist() }, 60000)
    ctx.effect(() => () => persist()) // flush on dispose

    const hourKey = (ts) => {
      const d = new Date(ts)
      d.setMinutes(0, 0, 0)
      return d.getTime()
    }
    const dayKey = (ts) => {
      const d = new Date(ts)
      d.setHours(0, 0, 0, 0)
      return d.getTime()
    }
    const emptyBucket = (ts) => ({
      ts,
      requests: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      reasoningTokens: 0,
      costCny: 0,
    })

    function recordUsage(options, usage) {
      const now = Date.now()
      const hk = hourKey(now)
      const dk = dayKey(now)
      let h = hourly.get(hk)
      if (!h) {
        h = emptyBucket(hk)
        hourly.set(hk, h)
      }
      let d = daily.get(dk)
      if (!d) {
        d = emptyBucket(dk)
        daily.set(dk, d)
      }
      const p = rateFor(options && options.model, now)
      const input = usage.inputTokens || 0
      const output = usage.outputTokens || 0
      const cacheRead = usage.cacheReadTokens || 0
      const cacheWrite = usage.cacheWriteTokens || 0
      const reasoning = usage.reasoningTokens || 0
      // cache hit is cheap, cache miss is full price, cache write is free; unit: CNY
      const cost = (input * p.miss + cacheRead * p.hit + output * p.output) / 1e6
      for (const b of [h, d]) {
        b.requests += 1
        b.inputTokens += input
        b.outputTokens += output
        b.cacheReadTokens += cacheRead
        b.cacheWriteTokens += cacheWrite
        b.reasoningTokens += reasoning
        b.costCny += cost
      }
      for (const k of hourly.keys()) if (k < now - HOURLY_KEEP_MS) hourly.delete(k)
      for (const k of daily.keys()) if (k < now - DAILY_KEEP_MS) daily.delete(k)
      dirty = true
    }

    // Listen to every real model call. This is a waterfall event: MUST call
    // next() and forward the stream, otherwise the model call breaks.
    ctx.on('llm/stream', (options, next) => {
      const inner = next()
      return (async function* () {
        for await (const chunk of inner) {
          if (chunk && chunk.type === 'usage' && chunk.usage) {
            try {
              recordUsage(options, chunk.usage)
            } catch (e) {
              // accounting must never break the stream
            }
          }
          yield chunk
        }
      })()
    })

    // ── balance ──────────────────────────────────────────────────────────────
    // Reuse the deployment's own DeepSeek credential. `web.fetch` cannot send
    // an Authorization header, so we shell out to curl via the subprocess seam.
    let balanceCache = { ok: false, error: 'not fetched yet', fetchedAt: 0 }

    async function fetchBalance(force) {
      if (!force && balanceCache.fetchedAt && Date.now() - balanceCache.fetchedAt < 30000) {
        return balanceCache
      }
      const credentials = ctx.get('credentials')
      const subprocess = ctx.get('subprocess')
      if (!credentials || !subprocess) {
        balanceCache = { ok: false, error: 'credentials/subprocess service unavailable', fetchedAt: Date.now() }
        return balanceCache
      }
      try {
        const cred = await credentials.resolve('DEEPSEEK_API_KEY')
        if (!cred) {
          balanceCache = { ok: false, error: 'DEEPSEEK_API_KEY credential not configured', fetchedAt: Date.now() }
          return balanceCache
        }
        const sandboxPolicy = ctx.get('sandboxPolicy')
        const cwd = sandboxPolicy ? sandboxPolicy.workspaceRoot : '/'
        const handle = subprocess.spawn({
          argv: [
            'curl', '-sS', '--max-time', '15',
            '-H', 'Authorization: Bearer ' + cred.value,
            'https://api.deepseek.com/user/balance',
          ],
          cwd,
          stdio: {
            stdin: 'ignore',
            stdout: { maxBytes: 65536 },
            stderr: { maxBytes: 4096 },
          },
          graceMs: 20000,
        })
        const outcome = await handle.done
        const out = handle.collected && handle.collected.stdout
          ? handle.collected.stdout.readFrom(0).text
          : ''
        if (outcome.exitCode !== 0 || !out) {
          const err = handle.collected && handle.collected.stderr
            ? handle.collected.stderr.readFrom(0).text
            : ''
          balanceCache = {
            ok: false,
            error: 'curl exit ' + String(outcome.exitCode) + (err ? ': ' + err.slice(0, 200) : ''),
            fetchedAt: Date.now(),
          }
          return balanceCache
        }
        const json = JSON.parse(out)
        const info = (json.balance_infos && json.balance_infos[0]) || {}
        balanceCache = {
          ok: true,
          isAvailable: !!json.is_available,
          currency: info.currency || 'CNY',
          total: info.total_balance,
          granted: info.granted_balance,
          toppedUp: info.topped_up_balance,
          fetchedAt: Date.now(),
        }
      } catch (e) {
        balanceCache = { ok: false, error: String((e && e.message) || e), fetchedAt: Date.now() }
      }
      return balanceCache
    }

    // refresh the balance every 60s silently; fetch once on startup
    ctx.interval(() => { fetchBalance(false).catch(() => {}) }, 60000)
    fetchBalance(false).catch(() => {})

    // ── snapshot assembly (shared by the HTTP route) ─────────────────────────
    async function buildSnapshot(force) {
      const balance = await fetchBalance(force)
      const now = Date.now()
      const hourlyList = [...hourly.values()]
        .filter((b) => b.ts >= now - 24 * 3600 * 1000)
        .sort((a, b) => a.ts - b.ts)
      const dailyList = [...daily.values()].sort((a, b) => a.ts - b.ts).slice(-14)
      const totals = hourlyList.reduce((acc, b) => {
        acc.requests += b.requests
        acc.inputTokens += b.inputTokens
        acc.outputTokens += b.outputTokens
        acc.cacheReadTokens += b.cacheReadTokens
        acc.cacheWriteTokens += b.cacheWriteTokens
        acc.reasoningTokens += b.reasoningTokens
        acc.costCny += b.costCny
        return acc
      }, emptyBucket(0))
      return {
        balance,
        startedAt,
        now,
        totals,
        hourly: hourlyList,
        daily: dailyList,
        pricingNote: 'Custo estimado em CNY a partir dos preços públicos da DeepSeek (cache hit / miss / saída; preços flat ou peak/off-peak conforme o horário UTC); apenas para referência.',
      }
    }

    // ── HTTP route for the Client half ───────────────────────────────────────
    // `?force=1` forces a fresh balance fetch; otherwise a 30s-cached value is
    // served. JSON body; errors surface as a 500 with a JSON error object.
    // `webServer` is a hard dependency (declared in inject), so the plugin
    // only activates once the web server is ready and the route always lands.
    ctx.effect(() => ctx.webServer.register({
      kind: 'exact',
      path: '/ds-api-usage/snapshot',
      handler: async (req, res) => {
        try {
          const force = new URL(req.url || '/', 'http://dsh.local').searchParams.get('force') === '1'
          const snapshot = await buildSnapshot(force)
          res.writeHead(200, { 'Content-Type': 'application/json' })
          res.end(JSON.stringify(snapshot))
        } catch (e) {
          res.writeHead(500, { 'Content-Type': 'application/json' })
          res.end(JSON.stringify({ ok: false, error: String((e && e.message) || e) }))
        }
      },
    }))
  },
}
